@echo off
del /s /q "C:\Program Files (x86)\Roblox\Versions\version-dcabc777160e4d68\PlatformContent\pc\textures\aluminum"
del /s /q "C:\Program Files (x86)\Roblox\Versions\version-dcabc777160e4d68\PlatformContent\pc\textures\brick"
del /s /q "C:\Program Files (x86)\Roblox\Versions\version-dcabc777160e4d68\PlatformContent\pc\textures\cobblestone"
del /s /q "C:\Program Files (x86)\Roblox\Versions\version-dcabc777160e4d68\PlatformContent\pc\textures\concrete"
del /s /q "C:\Program Files (x86)\Roblox\Versions\version-dcabc777160e4d68\PlatformContent\pc\textures\diamondplate"
del /s /q "C:\Program Files (x86)\Roblox\Versions\version-dcabc777160e4d68\PlatformContent\pc\textures\fabric"
del /s /q "C:\Program Files (x86)\Roblox\Versions\version-dcabc777160e4d68\PlatformContent\pc\textures\glass"
del /s /q "C:\Program Files (x86)\Roblox\Versions\version-dcabc777160e4d68\PlatformContent\pc\textures\granite"
del /s /q "C:\Program Files (x86)\Roblox\Versions\version-dcabc777160e4d68\PlatformContent\pc\textures\grass"
del /s /q "C:\Program Files (x86)\Roblox\Versions\version-dcabc777160e4d68\PlatformContent\pc\textures\ice"
del /s /q "C:\Program Files (x86)\Roblox\Versions\version-dcabc777160e4d68\PlatformContent\pc\textures\marble"
del /s /q "C:\Program Files (x86)\Roblox\Versions\version-dcabc777160e4d68\PlatformContent\pc\textures\metal"
del /s /q "C:\Program Files (x86)\Roblox\Versions\version-dcabc777160e4d68\PlatformContent\pc\textures\pebble"
del /s /q "C:\Program Files (x86)\Roblox\Versions\version-dcabc777160e4d68\PlatformContent\pc\textures\plastic"
del /s /q "C:\Program Files (x86)\Roblox\Versions\version-dcabc777160e4d68\PlatformContent\pc\textures\rust"
del /s /q "C:\Program Files (x86)\Roblox\Versions\version-dcabc777160e4d68\PlatformContent\pc\textures\sand"
del /s /q "C:\Program Files (x86)\Roblox\Versions\version-dcabc777160e4d68\PlatformContent\pc\textures\sky"
del /s /q "C:\Program Files (x86)\Roblox\Versions\version-dcabc777160e4d68\PlatformContent\pc\textures\slate"
del /s /q "C:\Program Files (x86)\Roblox\Versions\version-dcabc777160e4d68\PlatformContent\pc\textures\water"
del /s /q "C:\Program Files (x86)\Roblox\Versions\version-dcabc777160e4d68\PlatformContent\pc\textures\wood"
del /s /q "C:\Program Files (x86)\Roblox\Versions\version-dcabc777160e4d68\PlatformContent\pc\textures\woodplanks"
del /s /q "C:\Program Files (x86)\Roblox\Versions\version-dcabc777160e4d68\content\sky"
exit
